[build]
  publish = "dist"
  command = "npm run build"

[functions]
  directory = "netlify/functions"

# Environment variables for functions
[build.environment]
  # These will be available to both build and functions
  STRIPE_SECRET_KEY = "${VITE_STRIPE_SECRET_KEY}"
  STRIPE_PUBLIC_KEY = "${VITE_STRIPE_PUBLIC_KEY}"

# Redirects for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# CORS headers for API functions
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"